const data={
  meta:{title:'Asymmetry',subtitle:'NEURAL ARCHITECTURE EXPLORER',repo:'cheffer0723/asymmetry',sourceCommit:'f6c19febbda9609b3f29bc0dd048bf3c057c18cd',figma:'Asymmetry — Master System Map',mode:'READ-ONLY / DERIVED VIEW'},
  nodes:[
    {id:'product',g:'product',k:'PRODUCT OVERLAY',t:'ASYMMETRY',d:'One user-facing workspace spanning two separated security domains.',x:120,y:820,s:'implemented'},
    {id:'workspace',g:'product',k:'USER SURFACE',t:'Asymmetry Workspace',d:'Single usability boundary; protocol engines remain separately reviewable.',x:480,y:820,s:'implemented'},
    {id:'dead',g:'communication',k:'CAPABILITY DOMAIN',t:'DEAD DROP',d:'Private packet transport, mix routing, mailbox delivery, acknowledgments and metadata resistance.',x:820,y:510,s:'implemented'},
    {id:'zero',g:'value',k:'CAPABILITY DOMAIN',t:'ZERO-DARK',d:'Confidential value-transfer coordination, proof logic, settlement intent and non-custodial movement.',x:820,y:1130,s:'implemented'},
    {id:'contracts',g:'foundation',k:'FOUNDATION',t:'INTEGRATION CONTRACTS',d:'Narrow client boundaries keep protocol internals behind reviewable adapters.',x:1180,y:820,s:'implemented'},
    {id:'dead-client',g:'boundary',k:'BOUNDARY',t:'DeadDropClient',d:'createSendIntent → submit → acknowledge',x:1510,y:350,s:'modeled'},
    {id:'dead-gateway',g:'boundary',k:'PRODUCT GATEWAY',t:'Dead Drop Gateway',d:'Least-privilege gateway for the communication capability.',x:1510,y:570,s:'implemented'},
    {id:'dead-status',g:'communication',k:'USER FLOW',t:'Delivery Status',d:'intent → submitted → delivered → acknowledged',x:1510,y:790,s:'modeled'},
    {id:'zero-client',g:'boundary',k:'BOUNDARY',t:'ZeroDarkClient',d:'createRouteIntent → prepare → submit',x:1510,y:1080,s:'modeled'},
    {id:'wallet',g:'value',k:'CURRENT PRODUCT',t:'Wallet Control',d:'Workspace verifies wallet control and stops before live execution.',x:1510,y:1300,s:'implemented'},
    {id:'proof',g:'value',k:'EVIDENCE',t:'Proof Readiness',d:'Dev/testnet proof flow exists; production trusted setup remains incomplete.',x:1850,y:1160,s:'modeled'},
    {id:'settlement',g:'future',k:'FUTURE / GATED',t:'Settlement Status',d:'Reserved for reviewed submission and settlement status; not production-ready.',x:2190,y:1310,s:'unproven'},
    {id:'audit',g:'foundation',k:'AUDIT POSTURE',t:'Evidence Boundary',d:'Claims stay labeled implemented, tested, modeled, externally audited or unproven.',x:2550,y:1030,s:'tested'},
    {id:'sources',g:'foundation',k:'EVIDENCE',t:'Source Provenance',d:'Product overlay and capability evidence remain separately attributable.',x:2550,y:520,s:'tested'},
    {id:'dd-packet',g:'communication',k:'PROTOCOL CONCEPT',t:'Packet Transport',d:'Fixed-shape protected packet transport; product does not select protocol internals.',x:1140,y:250,s:'modeled'},
    {id:'dd-mix',g:'communication',k:'PROTOCOL CONCEPT',t:'Mix / Relay Layers',d:'Mix routing and relay behavior belong inside the Dead Drop security boundary.',x:1510,y:120,s:'modeled'},
    {id:'dd-mailbox',g:'communication',k:'PROTOCOL CONCEPT',t:'Mailbox Delivery',d:'Stored/retrieved delivery model; surfaced only through reviewed contracts.',x:1860,y:310,s:'modeled'},
    {id:'dd-ack',g:'communication',k:'PROTOCOL CONCEPT',t:'Recipient Acknowledgment',d:'First-class delivery acknowledgment contract.',x:2190,y:430,s:'unproven'},
    {id:'zd-route',g:'value',k:'PROTOCOL CONCEPT',t:'Route Intent',d:'Private transfer coordination begins as an intent, not a live execution.',x:1140,y:1390,s:'modeled'},
    {id:'zd-proof',g:'value',k:'PROTOCOL CONCEPT',t:'Commitment / Nullifier',d:'Cryptographic state model implemented but unaudited.',x:1850,y:1510,s:'modeled'},
    {id:'zd-circuit',g:'value',k:'PROTOCOL CONCEPT',t:'Groth16 Proof Flow',d:'Implemented in development/testnet flow; production setup is incomplete.',x:2190,y:1570,s:'modeled'},
    {id:'release',g:'foundation',k:'RELEASE GATE',t:'Production Readiness',d:'Independent audit, repeatable tests and operational review are required before production claims.',x:2880,y:760,s:'unproven'}
  ],
  edges:[
    ['product','workspace','core'],['workspace','dead','core'],['workspace','zero','core'],['workspace','contracts','core'],
    ['dead','contracts','contract'],['zero','contracts','contract'],['contracts','dead-client','contract'],['contracts','zero-client','contract'],
    ['dead','dd-packet','protocol'],['dd-packet','dd-mix','protocol'],['dd-mix','dd-mailbox','protocol'],['dd-mailbox','dd-ack','protocol'],
    ['dead','dead-client','contract'],['dead-client','dead-gateway','flow'],['dead-gateway','dead-status','flow'],['dead-status','audit','evidence'],
    ['zero','zero-client','contract'],['zero-client','wallet','flow'],['zero-client','zd-route','protocol'],['wallet','proof','evidence'],
    ['zd-route','zd-proof','protocol'],['zd-proof','zd-circuit','protocol'],['proof','settlement','flow'],['settlement','audit','evidence'],
    ['contracts','sources','evidence'],['dead','sources','evidence'],['zero','sources','evidence'],['audit','release','evidence'],['sources','release','evidence']
  ]
};

const app=document.querySelector('#app');
app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="eyebrow">ASYMMETRY / SYSTEM MAP</div><div class="title">NEURAL ARCHITECTURE EXPLORER</div><div class="subtitle">One product · two protected capability domains · narrow integration contracts</div></div><div class="top-actions"><button class="btn" id="fit">FIT</button><button class="btn" id="reset">RESET</button><button class="btn accent" id="clear">CLEAR</button></div></header><main class="workspace"><div class="canvas" id="canvas"><div class="stage" id="stage"><div class="ambient a1"></div><div class="ambient a2"></div><div class="zone z1"><span>PRODUCT OVERLAY</span></div><div class="zone z2"><span>DEAD DROP / COMMUNICATION</span></div><div class="zone z3"><span>ZERO-DARK / VALUE</span></div><div class="hero"><div class="eyebrow">AUDIT-FRIENDLY DERIVED VIEW</div><h1>ASYMMETRY</h1><p>Architecture rendered as a living neural map. Select any node to expose its immediate neighborhood.</p><div class="hero-rule"><span></span> CURRENT MASTER SNAPSHOT <b>${data.meta.sourceCommit.slice(0,9)}</b></div></div><div class="legend"><div class="legend-title">DOMAIN / EVIDENCE</div><div><i class="dot product"></i>PRODUCT</div><div><i class="dot communication"></i>COMMUNICATION</div><div><i class="dot value"></i>VALUE</div><div><i class="dot boundary"></i>BOUNDARY</div><div><i class="dot foundation"></i>FOUNDATION / EVIDENCE</div><div><i class="dot future"></i>FUTURE / GATED</div></div><svg id="links" aria-hidden="true"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="glowStrong"><feGaussianBlur stdDeviation="8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#bdf5ff"/></marker></defs></svg><div id="nodes"></div></div></div><div class="badge">READ-ONLY · SOURCE SNAPSHOT</div><div class="toolbar"><button class="btn" id="zin">＋</button><button class="btn" id="zout">−</button></div><aside class="inspector" id="inspector"><div class="ins-empty"><span class="scan"></span><div class="meta">SELECT A NODE</div><h3>Architecture Inspector</h3><p>Click a node. Its direct relationships will ignite while unrelated architecture recedes.</p></div></aside><div class="footer">SOURCE: ${data.meta.repo} · ${data.meta.sourceCommit.slice(0,9)} · VISUAL BUILD</div></main></div>`;

const canvas=document.querySelector('#canvas'),stage=document.querySelector('#stage'),nodesEl=document.querySelector('#nodes'),svg=document.querySelector('#links'),inspector=document.querySelector('#inspector');
const map=Object.fromEntries(data.nodes.map(n=>[n.id,n]));const nodeEls={};const edgeEls=[];let selected=null;
function center(n){return{x:n.x+112,y:n.y+54}}
function curve(a,b){const A=center(map[a]),B=center(map[b]),dx=Math.max(120,Math.abs(B.x-A.x)*.42);return`M ${A.x} ${A.y} C ${A.x+dx} ${A.y}, ${B.x-dx} ${B.y}, ${B.x} ${B.y}`}
function render(){
 nodesEl.innerHTML='';svg.querySelectorAll('.edge,.edge-hit').forEach(x=>x.remove());
 data.nodes.forEach(n=>{const el=document.createElement('button');el.className=`node ${n.g}`;el.style.left=n.x+'px';el.style.top=n.y+'px';el.dataset.id=n.id;el.innerHTML=`<span class="node-glow"></span><span class="kicker">${n.k}</span><strong>${n.t}</strong><p>${n.d}</p><span class="status ${n.s}">${n.s.toUpperCase()}</span><span class="port"></span>`;el.onclick=e=>{e.stopPropagation();select(n.id)};nodesEl.appendChild(el);nodeEls[n.id]=el});
 data.edges.forEach((e,i)=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.classList.add('edge',e[2]);p.dataset.a=e[0];p.dataset.b=e[1];p.dataset.i=i;p.setAttribute('d',curve(e[0],e[1]));p.setAttribute('marker-end','url(#arrow)');svg.appendChild(p);edgeEls.push(p)});
}
function select(id){selected=id;const related=new Set([id]);data.edges.forEach(([a,b])=>{if(a===id)related.add(b);if(b===id)related.add(a)});data.nodes.forEach(n=>nodeEls[n.id].classList.toggle('dim',!related.has(n.id)));data.nodes.forEach(n=>nodeEls[n.id].classList.toggle('selected',n.id===id));edgeEls.forEach(p=>{const hot=p.dataset.a===id||p.dataset.b===id;p.classList.toggle('dim',!hot);p.classList.toggle('hot',hot)});const n=map[id];const links=data.edges.filter(e=>e[0]===id||e[1]===id).map(e=>map[e[0]===id?e[1]:e[0]]);inspector.innerHTML=`<div class="ins-head"><div><div class="meta">${n.k}</div><h3>${n.t}</h3></div><button class="close" id="close">×</button></div><p>${n.d}</p><div class="inspect-status ${n.s}">${n.s.toUpperCase()}</div><div class="rel-title">DIRECT RELATIONSHIPS · ${links.length}</div><div class="rel-list">${links.map(x=>`<button class="tag" data-jump="${x.id}">${x.t}<small>${x.k}</small></button>`).join('')}</div>`;document.querySelector('#close').onclick=clear;inspector.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>select(b.dataset.jump))}
function clear(){selected=null;data.nodes.forEach(n=>nodeEls[n.id].classList.remove('dim','selected'));edgeEls.forEach(p=>p.classList.remove('dim','hot'));inspector.innerHTML='<div class="ins-empty"><span class="scan"></span><div class="meta">SELECT A NODE</div><h3>Architecture Inspector</h3><p>Click a node. Its direct relationships will ignite while unrelated architecture recedes.</p></div>'}
let scale=1,tx=0,ty=0,drag=false,sx=0,sy=0,stx=0,sty=0;
function apply(){stage.style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`}
function fit(){const s=Math.min(canvas.clientWidth/3100,canvas.clientHeight/1800)*.92;scale=Math.max(.38,Math.min(1.08,s));tx=(canvas.clientWidth-3100*scale)/2;ty=(canvas.clientHeight-1800*scale)/2;apply()}
function zoomAt(f,cx,cy){const ns=Math.max(.38,Math.min(1.75,scale*f)),r=ns/scale;tx=cx-(cx-tx)*r;ty=cy-(cy-ty)*r;scale=ns;apply()}
canvas.addEventListener('pointerdown',e=>{if(e.target.closest('.node,.btn,.inspector,.tag'))return;drag=true;sx=e.clientX;sy=e.clientY;stx=tx;sty=ty;canvas.classList.add('dragging');canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(drag){tx=stx+e.clientX-sx;ty=sty+e.clientY-sy;apply()}});canvas.addEventListener('pointerup',()=>{drag=false;canvas.classList.remove('dragging')});canvas.addEventListener('pointercancel',()=>{drag=false;canvas.classList.remove('dragging')});canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoomAt(e.deltaY<0?1.1:.9,e.clientX-r.left,e.clientY-r.top)},{passive:false});canvas.addEventListener('click',clear);
document.querySelector('#fit').onclick=fit;document.querySelector('#reset').onclick=()=>{scale=1;tx=0;ty=0;apply()};document.querySelector('#clear').onclick=clear;document.querySelector('#zin').onclick=()=>zoomAt(1.2,canvas.clientWidth/2,canvas.clientHeight/2);document.querySelector('#zout').onclick=()=>zoomAt(.83,canvas.clientWidth/2,canvas.clientHeight/2);
render();requestAnimationFrame(fit);window.addEventListener('resize',fit);
